Myproject/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),  
]

todo/urls.py
from django.urls import path 
from . import views



app_name = 'todo'

urlpatterns = [
    path('TODO', views.index, name='index'),
    path ('add/', views.addTodo, name='add'),
    path ('complete/<todo_id>/', views.completeTodo, name='complete'),
    path ('edit/<todo_id>/', views.edit , name='edit'), 
    path ('delete/', views.deleteCompleted, name='delete'),
    path ('deleteAll/', views.deleteAll, name='deleteAll'),
    path('todolist/', views.Todolist, name='todolist'), 
    
]

todo/models.py
from django.db import models
from django.utils import timezone




class Todo(models.Model): 
    text = models.TextField(max_length=500)
    complete = models.BooleanField(default=False) 
    date = models.DateField(default=timezone.now)
    description = models.TextField(max_length=500, blank=True) 
    
    
   
    def __str__(self):
        return self.text
    
    # def get_absolute_url(self):
    #     return reverse('edit', kwargs={'id': self.id})

todo/forms.py
from django import forms
from django.forms import ModelForm
from .models import Todo
from django.utils import timezone

# from django.conf import settings


class DateInput(forms.DateInput): 
    input_type = 'date'


class TodoForm(forms.ModelForm): 
    class Meta: 
        model = Todo


        fields = [
            'text', 
            'date',
            'description', 
        ]
        widgets = {            
            'text' : forms.TextInput(
                attrs = {
                    'class' : 'form-control',
                    'id'    : 'text', 
                    'placeholder' : 'Enter todo', 
                    'aria-lable' : 'Todo', 
                    'aria-describedby' : 'add-btn', 
                    }
                 ), 
        
        
            'date' : DateInput(
                    attrs = {
                        'class' : 'form-control', 
                        'id'     : 'date', 
                        'placeholder' : 'Select a date'
                    }
            ), 

              
            'description' : forms.Textarea( 
                    attrs = {
                        
                        "class": "form-control", 
                        "id": "description", 
                        "name": "description", 
                        "rows": 5, 
                        "cols": 20, 
                    }
            )
        
        }

# class EditForm(forms.ModelForm):
#     class Meta: 
#         model = Todo
#         fields = "__all__" 

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.views.decorators.http import require_POST
from .models import Todo
from django.http import JsonResponse
from .forms import TodoForm
from django.forms import ModelForm
from django.views.generic.edit import UpdateView


def index(request): 
    todo_list = Todo.objects.all().order_by('id')
    form = TodoForm()
    print(todo_list)

    context = {'todo_list'  : todo_list, 'form' : form}
    return render(request, 'todo/index.html', context)

# @require_POST
def addTodo(request): 
    form = TodoForm(request.POST) 
    if form.is_valid():
        new_todo=Todo(text=request.POST['text'], date=request.POST['date'], description=request.POST['description'])
        new_todo.save()
        return redirect('todo:index')
    return render(request, 'todo/index.html', {'form':form})

    

def completeTodo(request, todo_id): 
    todo = Todo.objects.get(pk=todo_id)
    todo.complete = not todo.complete
    todo.save() 
    return redirect('todo:index')


def deleteCompleted(request): 
    Todo.objects.filter(complete__exact=True).delete()
    return redirect('todo:index')

def deleteAll(request): 
    Todo.objects.all().delete()

    return redirect('todo:index')

           

def edit(request, todo_id):

    instance = get_object_or_404(Todo, id=todo_id)
    form = TodoForm(instance=instance)
    if request.method == "POST": 


        text = request.POST['text']
        date = request.POST['date']
        description = request.POST['description']


        form = TodoForm(request.POST, instance=instance)
        if form.is_valid(): 
            instance = form.save(commit=True)
            return redirect('todo:index')

    return render(request, 'todo/edit.html', {'form':form})
    

def Todolist(request): 
    todo_list = Todo.objects.all().order_by('id')
    form = TodoForm()
    print(todo_list)

    context = {'todo_list'  : todo_list, 'form' : form}
    return render(request, 'todo/list.html', context)


# def addTodo(request): 
#     form = TodoForm()
#     if request == 'POST':
        

todo/templates/todo/edit.html
    <form action="" method="POST" role="form">
        {% csrf_token %}	
            {{form.as_p}}		
        <div class= "input-group-btn"> 
            <button type="submit" class="btn btn-default"> Save </button>
        </div>
    </form>

todo/templates/todo/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>ToDo App</title>
		
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
		
	</head>
	<body>

		<div class="container">
			
			<div class="row">
				<div class="col-md-12" >
					<h2> Your today's list </h2>
					<form action="{% url 'todo:add'%}" id ="myform" method="POST" role="form">
						{% csrf_token %}	
					    {{form.as_p}}		
					<div class="row">
								<div class="col-md-12 text-right">
										<button type="submit" id="btnadd" class="btn btn-success"> Add </button>
								</div>
					</div>
					<div class="row mt-4">
						<div class="col-lg-12 text-right mb-4">
									<a class="btn btn-danger btn-sm" href="{% url 'todo:delete' %}"> DELETE COMPLETED</a>
									<a class="btn btn-danger btn-sm" href="{% url 'todo:deleteAll' %}">DELETE ALL</a>
						</div>
					</div>


					<table class="table table-border">
						<tbody>
							<thead>
								<tr>
									<th>
										Text
									</th>
									<th>Date</th>
									<th>Edit</th>
								</tr>
							</thead>
							{% for todo in todo_list %}
							<tr>
								<td>
									<a href="{% url 'todo:complete' todo.id %}"> 
									{% if todo.complete %}	
									<strike>{{ todo.text }}</strike>
											{% else %}	
											{{ todo.text }}
											{%endif%}
								</a>
								</td>
								<td>{{ todo.date}}</td>
							<td>
	
								<a class="btn btn-warning btn-sm" href="{% url 'todo:edit' todo.id%}">Edit</a> 
				
									
							</td>
							</tr>
							{% endfor %}
						</tbody>
				</div>
			</div>
			<footer>
				<div class="row pad">
					</div>
				</div>
			</footer>
		</div>
	</div>/
	</body>

	<script
  src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
	<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script> -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
	<script type="text/javascript"> 
	
	$(document).ready(function(){
		var $form = $('#myform');
		$('#btnadd').click(function(e){
			e.preventDefault();
			var $formData = $form.serialize();
			console.log($formData);
			$.ajax({
				method: 'POST', 
				url: '/add/',
				data: $formData,
				success: handleSuccess,
				error: handleError,   


			});
			function handleSuccess(data){
				getList();
			}
			function handleError(){
				alert('failure');
			}
			


		});
		
		
		});

		function getList() {
			$.ajax({
				method: 'GET', 
				url: '/TODO', 
				success: function(json){
					alert(json);
					
				}			

		
	});
}
		
	
	</script>	
	




</html>

todo/templates/todo/list.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>ToDo App</title>
		
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
		
	</head>
	<body>

		<div class="container">
			
			<div class="row">
				<div class="col-md-12" >
					<h2> Your today's list </h2>

					<table class="table table-border">
						<tbody>
							<thead>
								<tr>
									<th>
										Text
									</th>
									<th>Date</th>
									<th>Edit</th>
								</tr>
							</thead>
							{% for todo in todo_list %}
							<tr>
								<td>	
									{{ todo.text }}	
								</td>
								<td>{{ todo.date}}</td>
							<td>
								<a class="btn btn-warning btn-sm" href="{% url 'todo:edit' todo.id%}">Edit</a> 		
							</td>
							</tr>
							{% endfor %}
						</tbody>
				</div>
			</div>
			<footer>
				<div class="row pad">
					</div>
				</div>
			</footer>
		</div>
	</div>
	</body>

	<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
	<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script> -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>

</html>